######################## default configuration ####################
# The base URL of your site (required). This will be prepended to all relative URLs.
baseURL = "https://prodojo.org"
# disable some pages for now
disableKinds = ["taxonomy", "term"]
# Title of your website (required).
title = "Prodojo"
# Your theme name
theme = "hugoplate"
# Default time zone for time stamps; use any valid tz database name: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
timeZone = "Asia/Calcutta"
# post excerpt
summaryLength = 10 # see https://gohugo.io/content-management/excerpts/
# disable language
disableLanguages = [

] # example: ["fr"] for disable french language. see https://gohugo.io/content-management/multilingual/ 
hasCJKLanguage = false #  If hasCJKLanguage true, auto-detect Chinese/Japanese/Korean Languages in the content. see: https://gohugo.io/getting-started/configuration/#hascjklanguage
# default language
defaultContentLanguage = 'en'
# defaultContentLanguageInSubdir need to be true if you want to use the language code as a subdirectory and language specific 404 page
defaultContentLanguageInSubdir = false
# Add robots.txt
enableRobotsTXT = true

########################### Services #############################
[services]
[services.googleAnalytics]
ID = 'G-7P3ZFNVV0J' # see https://gohugo.io/templates/internal/#configure-google-analytics

[services.disqus]
shortname = 'themefisher-template' # we use disqus to show comments in blog posts . To install disqus please follow this tutorial https://portfolio.peter-baumgartner.net/2017/09/10/how-to-install-disqus-on-hugo/

########################## Permalinks ############################
[permalinks.page]
"pages" = "/:slugorfilename/"

########################## Pagination ############################
[pagination]
disableAliases = false
pagerSize = 10
path = 'page'

############################# Modules ############################
[module]
[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "hugo_stats.json"
target = "assets/watching/hugo_stats.json"

############################# Build ##############################
[build]
noJSConfigInAssets = false
useResourceCacheWhen = 'fallback'
[build.buildStats]
enable = true
[[build.cachebusters]]
source = 'assets/watching/hugo_stats\.json'
target = 'style\.css'
[[build.cachebusters]]
source = '(postcss|tailwind)\.config\.js'
target = 'css'
[[build.cachebusters]]
source = 'assets/.*\.(js|ts|jsx|tsx)'
target = 'js'
[[build.cachebusters]]
source = 'assets/.*\.(css|scss|sass)'
target = 'css'
[[build.cachebusters]]
source = 'data/.*\.(.*)$'
target = 'css'
[[build.cachebusters]]
source = 'assets/.*\.(.*)$'
target = '$1'

############################# Outputs ############################
[outputs]
home = ["HTML", "RSS", "WebAppManifest", "SearchIndex"]

############################# Imaging ############################
[imaging]
# See https://github.com/disintegration/imaging
# Default JPEG or WebP quality setting. Default is 75.
quality = 80
resampleFilter = "Lanczos"

############################ Caches ##############################
[caches]
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"

############################ Markup ##############################
[markup]
[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = 'monokai' # see https://xyproto.github.io/splash/docs/all.html

[markup.tableOfContents]
endLevel = 5
ordered = true
startLevel = 2

########################### Media types ###########################
[mediaTypes]
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]

########################### Output Format ##########################
[outputFormats]
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"

[outputFormats.SearchIndex]
baseName = "searchindex"
isPlainText = true
mediaType = "application/json"
notAlternative = true

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
lazy = true
link = "plugins/swiper/swiper-bundle.css"
[[params.plugins.css]]
lazy = true
link = "plugins/glightbox/glightbox.css"
[[params.plugins.css]]
lazy = true
link = "plugins/font-awesome/v6/brands.css"
[[params.plugins.css]]
lazy = true
link = "plugins/font-awesome/v6/solid.css"
[[params.plugins.css]]
lazy = true
link = "plugins/font-awesome/v6/icons.css"

# JS Plugins
[[params.plugins.js]]
lazy = false
link = "js/search.js"
[[params.plugins.js]]
lazy = false
link = "plugins/swiper/swiper-bundle.js"
[[params.plugins.js]]
lazy = false
link = "plugins/cookie.js"
[[params.plugins.js]]
lazy = true
link = "plugins/glightbox/glightbox.js"
[[params.plugins.js]]
lazy = true
link = "js/gallery-slider.js"
[[params.plugins.js]]
lazy = true
link = "js/accordion.js"
[[params.plugins.js]]
lazy = true
link = "js/tab.js"
[[params.plugins.js]]
lazy = true
link = "js/modal.js"
[[params.plugins.js]]
lazy = true
link = "plugins/youtube-lite.js"
